### ISSUE TITLE
Width and Height of SVG

### ISSUE THREAD

**Issue by Mubashshir** [czeckd/angular-svg-icon#1]
width and height property of svg element is not working.

**Comment by czeckd** [comment]
What browser and version are you using? Depending on the browser, you may need to adjust the CSS.

Note for this to work, the height/width should be handled by CSS and not the SVG. If you leave the height and width attributes in the SVG, they will override the CSS styling for height and width. Can you post the SVG you are using?

**Comment by czeckd** [comment]
Are you setting the height/width on the svg-icon element itself? That may be where the problem is. It works when you set it on a container for the svg. Here's an example:

`<div style="width:75px;fill:rgb(120,120,120);">`
`<svg-icon src="images/eye.svg">`
 `</svg-icon></div>`

You could set the fill as a style on `<svg-icon>`, for example, but height and width would still need to be set on the `div` container of `<svg-icon>`.

**Comment by Mubashshir** [comment]
Thanks @czeckd 
Actually i was setting the width and height on the svg-icon itself
