### ISSUE TITLE
Component has extra height 

### ISSUE THREAD

**Issue by Serene47** [czeckd/angular-svg-icon#124]
I am using `svg-icon` 10.0.0 for loading a 24 * 24 `svg` 

but when it loads the `svg` element has the same height and width but `svg-icon` component has a height of 29 px, and this makes my alignments go wrong.

Relevant screenshot is attached

![Screenshot from 2021-02-24 11-01-16](https://user-images.githubusercontent.com/24951939/108952617-cb692a80-768f-11eb-9319-1ccd972015ce.png)

**Comment by czeckd** [comment]
It is looks like the font-size or possibly line-height used with the back button is interfering.  To confirm this, see if the 'extra height' happens if the `svg-icon` is used outside of your button mark-up.

You can explicitly set the height of the SVG in the `svg-icon` inside the button by doing something like the following:

```html
<svg-icon src="assets/images/left-arrow.svg" [svgStyle]="{'height.px':'24'}"></svg-icon>
```

**Comment by czeckd** [comment]
Yes, it is the font-size. The `svgStyle` isn't needed. Since the SVG is a 24x24 if you hover over the `svg`. The `svg-icon` is getting its height from the line-height set by the font.

**Comment by Serene47** [comment]
Thanks for the quick reply 

I have previously replaced `svg-icon` with pure `svg` , and now added it back, but this time very different result, width changed to 32 and height remained 29 

![Screenshot from 2021-02-24 12-04-27](https://user-images.githubusercontent.com/24951939/108958383-e7bd9500-7698-11eb-87bb-176406e960fe.png)

I applied line-height to 1 but for both `button` and `svg-icon`  , but things are no different . Also setting ` [svgStyle]="{'height.px':'24'}"` has no effect

The icon placed outside of button has dimension 24 * 20 

![Screenshot from 2021-02-24 12-18-37](https://user-images.githubusercontent.com/24951939/108959596-9ca48180-769a-11eb-8788-2f2129d42b22.png)

**Comment by czeckd** [comment]
The size of `svg-icon` is determined by the button's font-size. The size of `svg-icon` is not the size of the `svg` it loads. To confirm this hover over the `svg` element inside the `svg-icon`.

If you want to explicitly set the height of the `svg-icon` to be 24px, you will need to adjust its style. For example, this might work:
```html
<svg-icon src="assets/images/left-arrow.svg" style="font-size:21.5px;"></svg-icon>
```
That said, the alignment isn't being caused by `svg-icon`, it is being caused by the font-size being used on the back-button style.

**Comment by Serene47** [comment]
It's been sometime after I opened the issue, 

I recently was able to remove the extra height from `svg-icon` by setting this  CSS rule in the global stylesheet 
`svg-icon svg {
  vertical-align : middle;
}`
