### ISSUE TITLE
Security & Performance/Implementation - DomSanitizer&SafeResourceUrl + Fetch vs HTTPClient

### ISSUE THREAD

**Issue by tsavo-vdb-knott** [czeckd/angular-svg-icon#126]
@czeckd Thanks for the wonderful library my friend! 

Quick question per @johanchouquet's thought: 

> Is it OK to use it just like that ? If we take as an example the repo `angular/material2`, they use quite a lot the built-in `DomSanitizer, SafeResourceUrl`. Why don't you do the same. Does the application becomes less secure if we don't use those ?

Is there any security to be concerned about in your library when not using those angular resource/DOM cleaners. I also am wondering if there is a way for this to be used without HTTP Client and just through the native Fetch API? If that was the case, given the HTTP Client may do some type of DomSanitizer/SafeResourceURL work internally, would we need to use those modules explicitly when bringing something down with fetch?

Cheers - T

**Comment by czeckd** [comment]
First off, I am not a security expert so take my answer with that in mind. For anyone who wants true recommendations, here's [Angular's Security Guide](https://angular.io/guide/security).

I omitted the DomSanitizer/SafeResourceURL from the design because it wasn't needed for my purposes when I built the library since I the SVG paths I was using were trusted and not user injectable. It may be need by other users of it and I welcome pull requests to update/ revise it. As I note in the library's documentation (at the end), I'm using an older methodology that Google abandoned in Angular Material back in the Angular 2, pre-release version of it, because of potential security concerns.

I'm sure it could be rewritten to use the native Fetch API, but I chose HttpClient because it was the Angular way of doing things and I was using the observables it provided to the library's advantage. The HttpClient does have an advantage with preventing [XSSI](https://angular.io/guide/security#xssi), automatically stripping out a common attack string. As such, I'm not interested in changing away from HttpClient.
