### ISSUE TITLE
Unload previous svg

### ISSUE THREAD

**Issue by rknbgl** [czeckd/angular-svg-icon#25]
If I try render icons in a for cycle trough this module, icon be the same as first.

code: <code>&lt;li *ngFor="let item of items"&gt;&lt;svg-icon src="{{'assets/img/Icons/' + item.image}}"&gt;&lt;/svg-icon&gt;&lt;/li&gt;</code>

![loaded](https://user-images.githubusercontent.com/13220436/29317886-3ce09258-81ce-11e7-961b-652fe6d50441.png)
![menu](https://user-images.githubusercontent.com/13220436/29317885-3cdd83ce-81ce-11e7-8979-a347fdbde084.png)

**Comment by czeckd** [comment]
Using the demo as a framework, I've not been able to reproduce what you are seeing. I've tried in Chrome, Firefox, and Safari.

HTML:
```html
<div *ngFor="let item of items">
    <svg-icon src="{{'images/' + item.image}}" style="width:25px;"></svg-icon>
</div>
```
Typescript:
```typescript
    items = [ { image: 'train.svg' }, { image: 'eye.svg' } ];
```

**Comment by czeckd** [comment]
Unreproducable.

**Comment by BenjaminDobler** [comment]
I think the problem might have been that the two svg files might contain the same ids for paths, etc.
Then you will see this result because the ids need to be unique per document. Otherwise they will overwrite other paths, shapes... I ran into this issue myself as most of the time graphic programs export svg data with paths like path-1. You will not have the issue oif you use img or object tag but i haven`t found a solution for use with this component. Maybe the component could (optionally) dynamically rewrite ids?

**Comment by czeckd** [comment]
@BenjaminDobler could you provide two example svgs that are causing this issue?
