### ISSUE TITLE
Height does not seem to work

### ISSUE THREAD

**Issue by NathanMol** [czeckd/angular-svg-icon#29]
I was trying to set he height property on the svg-icon element, but it is not working. Only width seems to be supported. It would be very usefull if height is also supported. In case both height and width are defined, the icon could be scaled.

**Comment by raphaelM-sudo** [comment]
It seems angular-svg-icon does not override the height and width attributes if they are already defined inside the .svg-file. So you probably have to remove those attributes inside the file in order to set them via css or styles.

**Comment by czeckd** [comment]
Read Sara Soueidan's article "[Making SVGs Responsive with CSS](https://tympanus.net/codrops/2014/08/19/making-svgs-responsive-with-css/)" for tips on making SVGs play nicely with CSS. The main goal of angular-svg-icon is to inline the svg. It does not alter the svg itself.

**Comment by jreichardt** [comment]
I don't see how the article helps in this case. It says 

> Once the width and height attributes are removed, all browsers assume a width equal to 100% and stretch the SVG horizontally to fit the width of its container.

So a .svg will always scale to the width of the container, unless you explicitly set the height attribute in the .svg file (to 100% for example). But then the inlined svg will _always_ scale to height. If you have a scenario where you want to use the same icon multiple times on a page, sometimes scaled to height, sometimes to width, you currently have to generate two versions of the same svg.

**Comment by czeckd** [comment]
I'll add a means for the svg-icon component styles to applied directly to the svg. This should allow for height style property to work. 

Another alternative would be to add a new attribute to the component for just innerHTML styles. I'm not going with this approach, because it won't be backwards compatible with existing usage. The downside is, however, it will create double borders if a border style is used on the component. 
```html
<!-- If styles were always applied directly regardless of desired or not. -->
<svg-icon src="assets/moon_o.svg"
  style="width:50px; fill:blue; border: 1px solid orange;"></svg-icon>
```
![image](https://user-images.githubusercontent.com/17859320/39389178-fab3fae2-4a3a-11e8-84d1-2e09ebb62acb.png)
So as a work-around, for the styles to be duplicated on the svg, I'll add an `apply` attribute as well. So in order for the styles to applied to the svg directly, it'll need `[apply]="true"` set. Without apply set, the svg-icon will display as it did in version 5.0 and earlier. 
```html
<!-- How it will work. Without apply=true, styles not set on svg directly. -->
<svg-icon src="assets/moon_o.svg"
  style="width:50px; fill:blue; border: 1px solid orange;"></svg-icon>
```
Like so:
![image](https://user-images.githubusercontent.com/17859320/39389249-6b5bd35a-4a3b-11e8-81bf-d8699f36bdd6.png)

But, with the apply=true, the styles will be also applied to the svg directly and height will then work. Like so: 
```html
<svg-icon src="assets/moon_o.svg" [apply]="true"
  [ngStyle]="{ height: '100px', fill: 'blue' }"></svg-icon>
```
![image](https://user-images.githubusercontent.com/17859320/39389101-42300308-4a3a-11e8-860f-c94a81f78a3d.png)

This, however, won't get an svg to stretch since the aspect ratio will be maintained. So, to override that, I'll add a `stretch` attribute as well to set `preserveAspectRatio="none"`.
```html
<svg-icon src="assets/moon_o.svg" [apply]="true" [stretch]="true"
   [ngStyle]="{ width: '50px', height: '100px', fill: 'blue' }"></svg-icon>
```
![image](https://user-images.githubusercontent.com/17859320/39389107-55fd76b8-4a3a-11e8-8c39-8fc6a42ddb58.png)

It should still work with `[ngStyle]` and `style` too.

**Comment by czeckd** [comment]
Taking my preferred approach of applying the svg-icon styles to the svg is problematic with stacked transform cancelling themselves out, double opacities, etc. So, instead of the approach described in https://github.com/czeckd/angular-svg-icon/issues/29#issuecomment-385122298, I'm going with #40 idea of adding a `[svgStyle]` attribute to pass styles directly to be set on the svg combined with the new`[stretch]` attribute.
