### ISSUE TITLE
Set class to svg

### ISSUE THREAD

**Issue by MickL** [czeckd/angular-svg-icon#58]
I am missing a option to set a class to the svg, e.g.:

```
<svg-icon src="images/eye.svg" [svgClass]="img-fluid my-icon is-active"></svg-icon>
```

which outputs:

```
<svg class="img-fluid my-icon is-active"></svg>
```

**Comment by czeckd** [comment]
Try the newly added `[applyCss]="true"` attribute:

```html
<svg-icon src="images/eye.svg" [applyCss]="true" class="img-fluid my-icon is-active"></svg-icon>
```
And see if that works for your use case.

**Comment by vaindil** [comment]
I just tried this in my code, using `[applyCss]="true"` has no effect with classes--my class is only applied to the `<svg-icon>` element.

**Comment by filipedtristao** [comment]
Hi @czeckd, its a really neat plugin!

About the applyCss, it only work if the applied class is specific for using with the svg element. In my case, i have class that's for general use, for example:

```css
.h-12 {
    height: 3rem;
}
```

If i use the applyCss like this:

```html
<svg-icon [applyCss]="true" class="h-12" src="assets/images/test.svg"></svg-icon>
```

It won't work, because my class don't apply the styles to the <svg> element. Is there any way to make the class applied to the ```<svg-icon>``` be transported to the ```<svg>``` tag?

**Comment by czeckd** [comment]
@MickL - this should work now in angular-svg-icon@9.1.0
